CREATE TABLE IF NOT EXISTS orders (
    id UUID PRIMARY KEY,
    order_code VARCHAR(100) NOT NULL UNIQUE,
    provider_id VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL,
    product_code VARCHAR(100) NOT NULL,
    product_description VARCHAR(500) NOT NULL,
    quantity INT NOT NULL,
    street VARCHAR(300) NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    postal_code VARCHAR(20) NOT NULL,
    country VARCHAR(100) NOT NULL,
    customer_name VARCHAR(200) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    email VARCHAR(200),
    expected_delivery_date DATE NOT NULL,
    special_conditions VARCHAR(500),
    estimated_dispatch_date DATE,
    rejection_reason VARCHAR(500),
    last_action_by VARCHAR(100),
    last_action_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0
);
